### ISSUE TITLE
PyPI wheel is not valid

### ISSUE THREAD

**Issue by benoit-pierre** [lapalme/pyrealb#2]
I don't know how it was generated, but it only contains the package metadata:
```shell
▸ unzip -l pyrealb-1.0-py3-none-any.whl
Archive:  pyrealb-1.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    35129  2021-12-13 01:48   pyrealb-1.0.dist-info/LICENSE
     3861  2021-12-13 01:48   pyrealb-1.0.dist-info/METADATA
       92  2021-12-13 01:48   pyrealb-1.0.dist-info/WHEEL
        1  2021-12-13 01:48   pyrealb-1.0.dist-info/top_level.txt
      376  2021-12-13 01:48   pyrealb-1.0.dist-info/RECORD
---------                     -------
    39459                     5 files
```

**Comment by benoit-pierre** [comment]
The source distribution is invalid too:
```shell
▸ tar tf pyrealb-1.0.tar.gz
pyrealb-1.0/
pyrealb-1.0/LICENSE
pyrealb-1.0/PKG-INFO
pyrealb-1.0/README.md
pyrealb-1.0/pyproject.toml
pyrealb-1.0/pyrealb.egg-info/
pyrealb-1.0/pyrealb.egg-info/PKG-INFO
pyrealb-1.0/pyrealb.egg-info/SOURCES.txt
pyrealb-1.0/pyrealb.egg-info/dependency_links.txt
pyrealb-1.0/pyrealb.egg-info/top_level.txt
pyrealb-1.0/setup.cfg
```

**Comment by lapalme** [comment]
Effectivement la version sur PyPi n'est pas bonne, je me suis planté lors de mon essai d'installation et je n'ai pas trouvé moyen de l'enlever. Essayez plutôt l'installation locale décrite dans le README.

Désolé pour la confusion

**Comment by benoit-pierre** [comment]
Vous pouvez supprimer les fichiers d'une version sur PyPI en passant par l'interface web. Ce serait bien de le faire, pour éviter à d'autres utilisateurs du perdre du temps à installer une version qui ne marche pas (d'autant plus que l'installation ce passe sans erreurs).

Par contre, il n'est pas possible de remplacer un fichier (pour des raisons de sécurité, les fichiers de chaque version sur PyPI sont immuables).

Pour les fichiers wheels, il est possible d'en générer un nouveau avec un numéro de build différent (`pyrealb-1.1-2-py3-none-any.whl`, `pyrealb-1.1-3-py3-none-any.whl`, etc...). 

Pour les distributions de type sources, c'est rappé...

Le plus simple serait de publier une nouvelle version mineure.

**Comment by lapalme** [comment]
Merci pour les suggestions.

Que signifie "c'est rappé" ? c'est bon ou pas???
Avez-vous pu l'essayer ? pour le moment, je suis le seul utilisateur et je suis curieux de savoir comment vous en avez entendu parler.

merci de votre intérêt

**Comment by benoit-pierre** [comment]
> Que signifie "c'est rappé" ? c'est bon ou pas???

Pas de mécanisme équivalent (build number) pour les distributions sources: la seule solution, publier une nouvelle version.

> Avez-vous pu l'essayer ? 

Oui, j'ai installé directement à partir de Github.

> pour le moment, je suis le seul utilisateur et je suis curieux de savoir comment vous en avez entendu parler.

A la suite d'une recherche de paquets sur PyPI.
