### ISSUE TITLE
How to create a constituency structure used as input for pyrealb?

### ISSUE THREAD

**Issue by DraymondHIT** [lapalme/pyrealb#3]
How to create a constituency structure used as input for pyrealb?

**Comment by lapalme** [comment]
HI

you can look at section 2 of [this document](https://arxiv.org/pdf/2012.15425.pdf)  
The notation is also briefly described in "docs/documentation.html"   
There are examples in "tests/dependencies_en.py" and "tests/dependencies_fr.py"  

thanks for your interest and do not hesitate to ask for more details

Guy

**Comment by DraymondHIT** [comment]
Thank you very much for your reply!

I want to transfer one sentence like
```
The white cat sits on the mat. 
```
to this
```
S(NP(D("the"),
     N("cat"),
     A("white"),
     VP(V("sit"),
        PP(P("on"),
           NP(D("the"),
              N("mat"))))))
```
and then I could use `pyrealb` for other operations.

How can I quickly do this?

**Comment by lapalme** [comment]
Kunze

> Le 7 juill. 2022 à 08:29, Kunze Li ***@***.***> a écrit :
> Thank you very much for your reply!
> 
> I want to transfer one sentence like
> 
> The white cat sits on the mat. 
> to this
> 
> S(NP(D("the"),
>      N("cat"),
>      A("white"),
>      VP(V("sit"),
>         PP(P("on"),
>            NP(D("the"),
>               N("mat"))))))
I understand that you want to "parse" a sentence to get a constituency (or a dependency) structure.
pyRealB is a "text realizer", not a parser, that starts from an internal structure to realize a sentence. It does the inverse of what you seem to want to do.

But we have done some work in this vein, look at the UDregenerator demo <https://github.com/rali-udem/jsRealB/tree/master/demos/UDregenerator> of jsRealB (which uses the same input formalism as pyRealB).  You can look at section 2.2 of this recent ACL paper <https://github.com/rali-udem/jsRealB/blob/master/demos/UDregenerator/LeBerre-QuestionGeneration.pdf>.

Did I understand you well?

Guy

**Comment by DraymondHIT** [comment]
Thank you very much for your help, Guy!
